# Generated by Django 4.1.6 on 2023-02-14 05:23

import apps.terraform_states.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('desc', models.TextField(default='', max_length=1024)),
                ('readonly', models.BooleanField(default=True)),
                ('state', models.JSONField(default=apps.terraform_states.models.__default_state__, verbose_name='Terraform State')),
            ],
            options={
                'db_table': 'k8single_terraform_states',
            },
        ),
    ]
