# Generated by Django 4.1.6 on 2023-02-14 15:15

import apps.terraform_states.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_states', '0002_alter_state_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('desc', models.TextField(default='', max_length=1024)),
                ('readonly', models.BooleanField(default=True)),
                ('state', models.JSONField(default=apps.terraform_states.models.__default_state__, verbose_name='Terraform State')),
            ],
            options={
                'db_table': 'k8single_terraform_states',
            },
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
