apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
## https://github.com/argoproj/argo-helm  //charts/argo-cd/
- name: argo-cd
  version: 5.14.1
  repository: https://argoproj.github.io/argo-helm/
  alias: cd
