basePath: /
info:
  contact:
    email: ghilbut@gmail.com
    name: ghilbut
  description: Manager for Applications on Kubernetes
  license:
    name: The GNU General Public License v3.0 (GPL v3)
    url: https://opensource.org/license/gpl-3-0/
  title: PolyKube API
  version: "1.0"
paths: {}
swagger: "2.0"
