basePath: /v1
info:
  contact:
    email: ghilbut@gmail.com
    name: ghilbut
  description: Manager for Applications on Kubernetes
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  title: K8Single API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
