apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo
  labels:
    ghilbut.com/category: network
    ghilbut.com/organization: ghilbut
spec:
  project: default
  source:
    ## https://github.com/metallb/metallb  //charts/metallb/
    repoURL: https://metallb.github.io/metallb/
    chart: metallb
    targetRevision: 0.13.7
    helm:
      values: |
        ---
      valueFiles:
        - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
---