version: "3.9"
networks:
  none:
    external: true
    name: none
services:
  memcached:
    image: memcached:1.6.18
    container_name: memcached
    ports:
      - 0.0.0.0:11211:11211
    read_only: true
    restart: always
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 0.0.0.0:5432:5432
    read_only: true
    restart: always
    tmpfs: /var/run/postgresql
    volumes:
      - .data/postgres:/var/lib/postgresql/data
  dex:
    depends_on:
      - postgres
    container_name: dex
    image: dexidp/dex:v2.36.0
    read_only: true
    restart: always
    ports:
      - 0.0.0.0:5556:5556
      - 0.0.0.0:5557:5557
      - 0.0.0.0:5558:5558
    tmpfs: /tmp
    volumes:
      - ./conf/dex:/etc/dex:ro
    environment:
      - GOOGLE_OAUTH2_CLIENT_ID
      - GOOGLE_OAUTH2_CLIENT_SECRET
  # vault:
  #   image: hashicorp/vault:1.13.2
  #   container_name: vault
  #   cap_add:
  #     - IPC_LOCK
  #   entrypoint: vault server -config=/vault/conf/local.hcl
  #   environment:
  #     - SKIP_CHOWN=true
  #     - SKIP_SETCAP=true
  #     - VAULT_ADDR=http://0.0.0.0:8200
  #   ports:
  #     - 0.0.0.0:8200:8200
  #   read_only: true
  #   restart: always
  #   volumes:
  #     - ./conf/vault:/vault/conf:ro
  #     - .data/vault/data:/vault/file
  #     - .data/vault/home:/home/vault
---
