ARG BUILDPLATFORM="linux/amd64"


FROM --platform=$BUILDPLATFORM golang:1.20.4 as builder

ENV CGO_ENABLED=0
RUN mkdir /app
WORKDIR /app
COPY . .
RUN go build -o viewer ./cmd/viewer


FROM scratch as release
LABEL co.ultary.image.authors="ghilbut@gmail.com"

EXPOSE 8080
COPY --from=builder /app/viewer /usr/local/bin/

CMD ["viewer"]
