apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  volumeName: prometheus-alertmanager
---
