apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
  volumeName: prometheus-server
---
