apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: grafana
      protocol: TCP
      name: grafana
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}